### ISSUE TITLE
tfollow bot not working

### ISSUE THREAD

**Issue by Pomidou** [whoisbaby/TwitchFollowers#20]
C:\Users\PC\Desktop\twbot\index.js:162
                    twitchID = res.users[0]._id
                                        ^

TypeError: Cannot read properties of undefined (reading '0')
    at C:\Users\PC\Desktop\twbot\index.js:162:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (C:\Users\PC\Desktop\twbot\index.js:158:13)

**Comment by Aryan9889** [comment]
deal with it

**Comment by whoisbaby** [comment]
true
