### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sppsupphack** [whoisbaby/TwitchFollowers#25]
return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://api.twitch.tv/kraken/users?login=dadadawds12e reason: Unexpected token G in JSON at position 0
    at C:\Users\ioumi\OneDrive\Desktop\TwitchFollowers-main\node_modules\node-fetch\lib\index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (C:\Users\ioumi\OneDrive\Desktop\TwitchFollowers-main\index.js:119:13) {
  type: 'invalid-json'
}

Node.js v18.15.0

**Comment by lrnsxdev** [comment]
+1

**Comment by LisaExists** [comment]
they changed kraken to helix

**Comment by LisaExists** [comment]
So just change `https://api.twitch.tv/kraken/users?login=${username}` to `https://api.twitch.tv/helix/users?login=${username}`

**Comment by epicharry** [comment]
> So just change `https://api.twitch.tv/kraken/users?login=${username}` to `https://api.twitch.tv/helix/users?login=${username}`

So I changed that but now I get this error please help how do I fix it?

![image](https://github.com/whoisbaby/TwitchFollowers/assets/38373650/430ad3af-7d30-4d4f-8884-6245754ffaf4)
