### ISSUE TITLE
error

### ISSUE THREAD

**Issue by insestito36** [whoisbaby/TwitchFollowers#27]
C:\Users\chris\TwitchFollowers>node index.js
C:\Users\chris\TwitchFollowers\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133
    const invalidToken = new DJSError(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\chris\TwitchFollowers\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\chris\TwitchFollowers\node_modules\discord.js\src\client\Client.js:223:21) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

Node.js v18.17.0

**Comment by TheDarkOneMC** [comment]
You need your own tokens
