### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]

### ISSUE THREAD

**Issue by FederTasche71** [whoisbaby/TwitchFollowers#3]
i have good tokens i dont no why this error comes

**Comment by Spiccy** [comment]
also getting same error
`
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:561:3)
    at new ClientRequest (_http_client.js:251:14)
    at Object.request (https.js:313:10)
    at Request.start (C:\Users\spiccy\Desktop\TwitchFollowers-main\node_modules\request\request.js:751:32)
    at Request.write (C:\Users\spiccy\Desktop\TwitchFollowers-main\node_modules\request\request.js:1491:10)
    at end (C:\Users\spiccy\Desktop\TwitchFollowers-main\node_modules\request\request.js:549:18)
    at Immediate._onImmediate (C:\Users\spiccy\Desktop\TwitchFollowers-main\node_modules\request\request.js:578:7)
    at processImmediate (internal/timers.js:461:21) {
  code: 'ERR_INVALID_CHAR'
  `

**Comment by whoisbaby** [comment]
you need good tokens
and you need tokens like h59fk2ph9if8jmto2nk2h431sqhpvo

**Comment by Lolgamer01** [comment]
i have tokens but not working

**Comment by Spiccy** [comment]
> you need good tokens
> and you need tokens like h59fk2ph9if8jmto2nk2h431sqhpvo

here's an example of the tokens im using 5y3xhxaq33pf0stodu2pmz7ycalwis still giving same error

**Comment by whoisbaby** [comment]
is it not banned? beacuse i see twitch massban tokens
